### PR TITLE
Check if any operands are null before extracting format types to avoid NPE

### PR DESCRIPTION
**Pull request by ToastNumber**
For [issue 55](https://github.com/Simulizer/Simulizer/issues/55)

### CODE REVIEW

**Comment by ToastNumber** [comment]
The CircleCI build's deploy key doesn't work any more. It compiles and runs fine locally. To release you'd probably need to fix CircleCI or disable it. I'll leave it up to you @mbway and @MichaelOultram. Feel free to implement a better fix! :)

**Comment by mbway** [comment]
I was able to recreate the crash with the program:
```asm
.text; lw $t0 ($t1)
```
placing the cursor to the right of $t1 and pressing backspace until `lw $t0 ()` at which point simulizer crashes.

and also typing this program out will cause the same crash
```asm
.text; lw $t0 ($
```



the root cause seems to be that the `baseAddress` grammar rule matches '()' because the `register` grammar rule matches the empty string when it shouldn't, because both rules for `register` begin with the `$` terminal symbol. I think that we would have hit this issue many times during development so I think something about Antlr must have changed to cause the parser to fail.

I would prefer to fix the parser so that register doesn't match the empty string, which would solve this issue, however I think your fix is more robust because there are other places where things might go wrong, resulting in `null` operands.

I've tried out your fix and it fixes things. Well done Kelsey :+1:

**Comment by mbway** [comment]
@MichaelOultram could you do something with the CI at some point?

**Comment by MichaelOultram** [comment]
Will look into fixing ci and merging this weekend.  I will try to set it up so it will auto release in case there are any more fixes/improvements to the project. Would have done it sooner, but I wasn't expecting any more changes to this repo. 

Good job on the fix!

On 15 November 2018 21:15:08 GMT, Matt Broadway <notifications@github.com> wrote:
>@MichaelOultram could you do something with the CI at some point?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Simulizer/Simulizer/pull/56#issuecomment-439192576

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mbway** [comment]
I can't find a way to catch syntax errors from Antlr without completely rewriting the parser, which I don't think is worth it. The string `()` creates the following parse tree when parsed as `baseAddress`:
selection_156
but with the following syntax errors:
```
line 1:1 missing {NAMED_REGISTER, NUMBERED_REGISTER} at ')'
line 1:2 missing ')' at '<EOF>'
```
except that Simulizer doesn't have access to these errors currently. Instead it tries to parse `baseAddress` and check whether the result or any of its children `null`. The problem is that in this case both the `baseAddress` and `register` symbols are not `null`. Only once you try to parse `NAMED_REGISTER` or `NUMBERED_REGISTER` do you get a `null`, however since these are terminal symbols I don't think there is a way (other than hard-coding or introspection to examine methods of the rule context objects, both of which are terrible approaches) to determine what terminal symbols are possible for the rule.

So unfortunately we should just handle the case where extracting the data from a `baseAddress` fails. The only difference should be a slightly less informative error message. Hopefully there aren't similar cases elsewhere in the parser where this behaviour causes problems.

**Comment by ToastNumber** [comment]
Thanks guys! If there's a fix for the parsing it can always be done in the future (maybe someone could take on Simulizer's issues as a final year project ;))

**Pull request merged**
